### ISSUE TITLE
Adicionar imagem para partilha nas redes

### ISSUE THREAD

**Issue by rlafuente** [transparenciahackday/dadosabertos.pt#10]
Falta-nos uma imagem que possa servir como preview do site nos shares de FB, Twitter et al.

Chega perfeitamente um screenshot da homepage!

**Comment by joao** [comment]
Acrescentada uma imagem para o Open Graph, suponho que o Twitter também suporte.

![og_share](https://cloud.githubusercontent.com/assets/1041/23561162/fb02c9e8-0034-11e7-9e6f-075cd585b2c1.png)
