### ISSUE TITLE
Colófon

### ISSUE THREAD

**Issue by marado** [transparenciahackday/dadosabertos.pt#4]
O colófon tem um "TODO: Organizar esta lista", mas não se entende que organização precisa (está com ordenação alfabética). O commit é do @rlafuente , talvez ele queira explicar? ;-)

**Comment by rlafuente** [comment]
Na altura, foi um dump dos nomes das pessoas que participaram no primeiro sprint. Mas sim, tal como está já podemos considerar que está organizado, vou retirar :-)
